version: '3'
services:
  app:
    build: .
    command: pm2-dev ./app/index.js
    environment:
      NODE_ENV: development
      NODE_APP_INSTANCE: ''
    depends_on:
      - mongodb
    ports:
      - '8080:8080'
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules

  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - '27017:27017'
